### ISSUE TITLE
An admin only cannot update process instance variables

### ISSUE THREAD

**Issue by cristianflorescu** [Activiti/activiti-cloud-runtime-bundle-service#246]
Steps to reproduce:

Login with an admin 
Select an app where the admin has the ACTIVITI_ADMIN role but no ACTIVITI_USER role
Select a process instance that has variables

Expect behaviour 
The admin should be able to update the variables

Current behaviour 
The admin is not able to update a variable

Related with https://issues.alfresco.com/jira/browse/ACTIVITI-2689, https://issues.alfresco.com/jira/browse/DW-1055

**Comment by cristianflorescu** [comment]
https://github.com/Activiti/activiti-cloud-runtime-bundle-service/blob/95ca4668a58cd0069d6a15311f0815d3aa8a80f9/activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-impl/src/main/java/org/activiti/cloud/services/rest/controllers/ProcessInstanceVariableAdminControllerImpl.java#L52
should be 
```private final ProcessAdminRuntime processAdminRuntime;```

**Comment by salaboy** [comment]
@cristianflorescu yes.. this looks like a bug.. can you please create the issue in GitHub.com/activiti/activiti and also you are pointing out the solution so a PR will be appreciated.

**Comment by salaboy** [comment]
@cristianflorescu also.. I notice that you are the author of that line ;) https://github.com/Activiti/activiti-cloud-runtime-bundle-service/blame/95ca4668a58cd0069d6a15311f0815d3aa8a80f9/activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-impl/src/main/java/org/activiti/cloud/services/rest/controllers/ProcessInstanceVariableAdminControllerImpl.java#L52

**Comment by cristianflorescu** [comment]
@salaboy yes I have to fix it..I can do it in current sprint, you can ask @balsarori to add https://issues.alfresco.com/jira/browse/ACTIVITI-2689 to current sprint
